### ISSUE TITLE
Request for featuring the website in a program I am publishing

### ISSUE THREAD

**Issue by AvanindraC** [anshuman2166AppproDev/Doge-Meet-Sources#1]
Hello, my name is Avanindra and I was wondering if I could link your website in my command line interface, rsbcli. https://github.com/AvanindraC/RSB  . A friend of mine named Shivang Yadav introduced me to it. The first time I saw it, I was mesmerized by it. It seems great and I would like to introduce other people to it. So can I add it as a preset in RSB?

**Comment by rudrathedev** [comment]
Sure, enjoy contributing to sources, If you need any help, dm me on Telegram : https://telegram.me/know_about_it

**Comment by AvanindraC** [comment]
Thanks a ton!
